2021-03-04 at 10:20:23 | INFO | call once
2021-03-04 at 10:20:30 | INFO | call once
2021-03-04 at 10:20:48 | INFO | call once
2021-03-04 at 10:21:31 | INFO | call once
2021-03-04 at 10:31:58 | INFO | call once
2021-03-04 at 10:40:23 | INFO | call once
2021-03-04 at 10:40:46 | INFO | call once
2021-03-04 at 10:40:54 | INFO | call once
2021-03-04 at 10:41:00 | INFO | call once
2021-03-04 at 10:41:09 | INFO | call once
2021-03-04 at 10:41:22 | INFO | call once
2021-03-04 at 10:41:29 | INFO | call once
2021-03-04 at 10:41:41 | INFO | call once
2021-03-04 at 10:41:50 | INFO | call once
2021-03-04 at 10:41:57 | INFO | call once
2021-03-04 at 10:42:07 | INFO | call once
2021-03-04 at 10:42:28 | INFO | call once
2021-03-04 at 10:42:40 | INFO | call once
2021-03-04 at 10:42:53 | INFO | call once
2021-03-04 at 11:15:38 | INFO | call once
2021-03-04 at 15:12:46 | ERROR | An error has been caught in function 'run', process 'MainProcess' (12282), thread 'ThreadPoolExecutor-0_0' (123145546481664):
Traceback (most recent call last):

  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1028e71f0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145546481664)>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1028e4ee0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145546481664)>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145546481664)>
    │    │        │    └ (<weakref at 0x110d059f0; to 'ThreadPoolExecutor' at 0x110cf15b0>, <_queue.SimpleQueue object at 0x110d83db0>, None, ())
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145546481664)>
    │    └ <function _worker at 0x110cdf820>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145546481664)>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x110cdf940>
    └ <concurrent.futures.thread._WorkItem object at 0x110cf1520>
> File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x110cf1520>
             │    │   │    └ [functools.partial(<function get_haiguan at 0x110bc8ee0>, db=<sqlalchemy.orm.session.Session object at 0x110ceab50>)]
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x110cf1520>
             │    └ <built-in method run of Context object at 0x103b00740>
             └ <concurrent.futures.thread._WorkItem object at 0x110cf1520>

  File "/Users/renchao/Documents/flm_workspace/mid/app/routers/haiguan.py", line 26, in get_haiguan
    r = crud.show_haiguan(db)
        │    │            └ <sqlalchemy.orm.session.Session object at 0x110ceab50>
        │    └ <function show_haiguan at 0x110bc88b0>
        └ <module 'app.db.crud' from '/Users/renchao/Documents/flm_workspace/mid/app/db/crud.py'>

TypeError: show_haiguan() missing 1 required positional argument: 'uuid'
2021-03-04 at 15:13:23 | ERROR | An error has been caught in function 'run', process 'MainProcess' (12418), thread 'ThreadPoolExecutor-0_0' (123145402601472):
Traceback (most recent call last):

  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x107f831f0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145402601472)>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x107f80ee0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145402601472)>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145402601472)>
    │    │        │    └ (<weakref at 0x11639e9a0; to 'ThreadPoolExecutor' at 0x116383dc0>, <_queue.SimpleQueue object at 0x116419d60>, None, ())
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145402601472)>
    │    └ <function _worker at 0x11637c820>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145402601472)>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x11637c940>
    └ <concurrent.futures.thread._WorkItem object at 0x11639d100>
> File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x11639d100>
             │    │   │    └ [functools.partial(<function get_haiguan at 0x116264ee0>, db=<sqlalchemy.orm.session.Session object at 0x11639d3a0>)]
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x11639d100>
             │    └ <built-in method run of Context object at 0x116384940>
             └ <concurrent.futures.thread._WorkItem object at 0x11639d100>

  File "/Users/renchao/Documents/flm_workspace/mid/app/routers/haiguan.py", line 26, in get_haiguan
    r = crud.show_haiguan(db)
        │    │            └ <sqlalchemy.orm.session.Session object at 0x11639d3a0>
        │    └ <function show_haiguan at 0x1162648b0>
        └ <module 'app.db.crud' from '/Users/renchao/Documents/flm_workspace/mid/app/db/crud.py'>

  File "/Users/renchao/Documents/flm_workspace/mid/app/db/crud.py", line 25, in show_haiguan
    mdata = one.to_dict()

UnboundLocalError: local variable 'one' referenced before assignment
2021-03-04 at 15:14:10 | INFO | (500, AttributeError("module 'app.db.models' has no attribute 'HaiguanItem'"), 'Exception in show_haiguan')
2021-03-04 at 15:14:10 | ERROR | An error has been caught in function 'run', process 'MainProcess' (12470), thread 'ThreadPoolExecutor-0_0' (123145391136768):
Traceback (most recent call last):

  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x107a611f0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145391136768)>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x107a5eee0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145391136768)>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145391136768)>
    │    │        │    └ (<weakref at 0x115e7e9a0; to 'ThreadPoolExecutor' at 0x115e67f40>, <_queue.SimpleQueue object at 0x115ef8d60>, None, ())
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145391136768)>
    │    └ <function _worker at 0x115e5a820>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145391136768)>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x115e5a940>
    └ <concurrent.futures.thread._WorkItem object at 0x115e673d0>
> File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x115e673d0>
             │    │   │    └ [functools.partial(<function get_haiguan at 0x115d44ee0>, db=<sqlalchemy.orm.session.Session object at 0x115e67af0>)]
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x115e673d0>
             │    └ <built-in method run of Context object at 0x115e62880>
             └ <concurrent.futures.thread._WorkItem object at 0x115e673d0>

  File "/Users/renchao/Documents/flm_workspace/mid/app/routers/haiguan.py", line 28, in get_haiguan
    return formate_response(r[0],r[1],r[2])
           │                │    │    └ (500, AttributeError("module 'app.db.models' has no attribute 'HaiguanItem'"), 'Exception in show_haiguan')
           │                │    └ (500, AttributeError("module 'app.db.models' has no attribute 'HaiguanItem'"), 'Exception in show_haiguan')
           │                └ (500, AttributeError("module 'app.db.models' has no attribute 'HaiguanItem'"), 'Exception in show_haiguan')
           └ <function formate_response at 0x10930cee0>

  File "/Users/renchao/Documents/flm_workspace/mid/app/utils/pycode.py", line 8, in formate_response
    return JSONResponse(
           └ <class 'starlette.responses.JSONResponse'>

  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
    │           │    │      └ {'code': 500, 'message': 'Exception in show_haiguan', 'data': AttributeError("module 'app.db.models' has no attribute 'Haigua...
    │           │    └ <function JSONResponse.render at 0x108d77af0>
    │           └ <starlette.responses.JSONResponse object at 0x115e5de50>
    └ <starlette.responses.JSONResponse object at 0x115e5de50>

  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 157, in render
    return json.dumps(
           │    └ <function dumps at 0x107fc6e50>
           └ <module 'json' from '/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__....

  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
           └ <class 'json.encoder.JSONEncoder'>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
             │    │          └ {'code': 500, 'message': 'Exception in show_haiguan', 'data': AttributeError("module 'app.db.models' has no attribute 'Haigua...
             │    └ <function JSONEncoder.iterencode at 0x107fc6dc0>
             └ <json.encoder.JSONEncoder object at 0x115e67190>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
           │           └ {'code': 500, 'message': 'Exception in show_haiguan', 'data': AttributeError("module 'app.db.models' has no attribute 'Haigua...
           └ <_json.Encoder object at 0x115e64fa0>
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

TypeError: Object of type AttributeError is not JSON serializable
2021-03-04 at 15:14:57 | INFO | (200, {'id': 574387, 'product_id': '01012100', 'product_name': '无数据', 'trade_country_id': 0, 'trade_country_name': '无数据', 'trade_id': 0, 'trade_name': '无数据', 'register_id': 0, 'register_name': '无数据', 'first_unit': '无数据', 'first_price': 0, 'second_unit': '无数据', 'second_price': 0, 'price': 0, 'year': 2020, 'start_month': 1, 'end_month': 12, 'import_type': 1, 'code_type': 1, 'month_type': 1, 'create_time': '2021-03-04 12:44:42'}, '')
